# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'David Raab'
tagline:          'Blogging about programming'
description:      ''
url:              http://sidburn.github.io
baseurl:          http://sidburn.github.io

author:
  name:           'David Raab'
  url:            http://sidburn.github.io

paginate:         10

github:
  repo:           https://github.com/sidburn/sidburn.github.io
